{
 "title": "Analytics antifraud metrcis",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "partyId", "label": "partyId", "query": "${VAR_PARTYID}" },
   { "name": "shopId", "label": "shopId", "query": "${VAR_SHOPID}" },
   { "name": "paymentCountry", "label": "paymentCountry", "query": "${VAR_PAYMENTCOUNTRY}" },
   { "name": "bin", "label": "bin", "query": "${VAR_BIN}" }
  ]
 },
 "panels": [
  {
   "title": "Payment",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "database": "fraud",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    sum(amount)/100 as sm,\n    count() as cnt,\n    avg(amount/100) as avg,\n    max(amount/100) as max,\n    currency\nFROM $table\nWHERE\n    toDate($from) <= timestamp\n    and toDate($to) >= timestamp\n    and $from <= toDateTime(eventTime)\n    and $to >= toDateTime(eventTime)\n    and match(partyId, '$partyId')\n    and match(shopId, '$shopId')\n    and status='captured' \nand shopId!='TEST'\nGROUP BY currency\nORDER BY cnt desc\nLIMIT 20",
     "rawQuery": "SELECT     sum(amount)/100 as sm,     count() as cnt,     avg(amount/100) as avg,     max(amount/100) as max,     currency FROM fraud.payment WHERE     toDate(1594117417) <= timestamp     and toDate(1594128219) >= timestamp     and 1594117417 <= toDateTime(eventTime)     and 1594128219 >= toDateTime(eventTime)     and match(partyId, '.')     and match(shopId, '.')     and status='captured'  and shopId!='TEST' GROUP BY currency ORDER BY cnt desc LIMIT 20",
     "round": "0s",
     "table": "payment"
    }
   ]
  },
  {
   "title": "Refunds",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "database": "fraud",
     "dateTimeColDataType": "eventTime",
     "dateTimeType": "TIMESTAMP",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    sum(amount / 100) as sm,\n    count() as cnt,\n    avg(amount / 100) as avg,\n    currency\nFROM $table\nWHERE\n    toDate($from) <= timestamp\n    and toDate($to) >= timestamp\n    and $from <= toDateTime(eventTime)\n    and $to >= toDateTime(eventTime)\n    and match(partyId, '$partyId')\n    and match(shopId, '$shopId')\n    and status = 'succeeded'\nand shopId!='TEST'\nGROUP BY currency\nORDER BY cnt desc\nLIMIT 20",
     "rawQuery": "SELECT     sum(amount / 100) as sm,     count() as cnt,     avg(amount / 100) as avg,     currency FROM fraud.refund WHERE     toDate(1594117417) <= timestamp     and toDate(1594128219) >= timestamp     and 1594117417 <= toDateTime(eventTime)     and 1594128219 >= toDateTime(eventTime)     and match(partyId, '.')     and match(shopId, '.')     and status = 'succeeded' and shopId!='TEST' GROUP BY currency ORDER BY cnt desc LIMIT 20",
     "round": "0s",
     "table": "refund"
    }
   ]
  },
  {
   "title": "Refunds by all",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "database": "analytic",
     "dateColDataType": "timestamp",
     "dateTimeColDataType": "eventTime",
     "dateTimeType": "TIMESTAMP",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\ntimestamp,\n    shopId,\n    currency,\n    sm_ref,\n    sm_all,\n    sm_ref * 100 / sm_all as percent\nFROM\n(\n    SELECT\n    timestamp,\n        shopId,\n        currency,\n        sum(amount / 100) as sm_ref\n    FROM fraud.refund\n    WHERE\n        toDate($from) <= timestamp\n        and toDate($to) >= timestamp\n        and match(partyId, '$partyId')\n        and match(shopId, '$shopId')\n        and status = 'succeeded'\n        and shopId != 'TEST'\n    GROUP BY\n        timestamp,\n        currency,\n        shopId\n)\nANY LEFT JOIN\n(\n    SELECT\n    timestamp,\n        shopId,\n        currency,\n        sum(amount / 100) as sm_all\n    FROM fraud.payment\n    WHERE\n        toDate($from) <= timestamp\n        and toDate($to) >= timestamp\n        and match(partyId, '$partyId')\n        and match(shopId, '$shopId')\n        and status = 'captured'\n        and shopId != 'TEST'\n    GROUP BY\n    timestamp,\n        currency,\n        shopId\n    HAVING  (sm_all > 100000 and currency='RUB') OR (sm_all > 1500 and currency='USD') OR (sm_all > 1500 and currency='EUR')\n) USING \ntimestamp,\n    shopId,\n    currency\nwhere sm_all > 0\nORDER BY percent DESC",
     "rawQuery": "SELECT timestamp,     shopId,     currency,     sm_ref,     sm_all,     sm_ref * 100 / sm_all as percent FROM (     SELECT     timestamp,         shopId,         currency,         sum(amount / 100) as sm_ref     FROM fraud.refund     WHERE         toDate(1594117417) <= timestamp         and toDate(1594128219) >= timestamp         and match(partyId, '.')         and match(shopId, '.')         and status = 'succeeded'         and shopId != 'TEST'     GROUP BY         timestamp,         currency,         shopId ) ANY LEFT JOIN (     SELECT     timestamp,         shopId,         currency,         sum(amount / 100) as sm_all     FROM fraud.payment     WHERE         toDate(1594117417) <= timestamp         and toDate(1594128219) >= timestamp         and match(partyId, '.')         and match(shopId, '.')         and status = 'captured'         and shopId != 'TEST'     GROUP BY     timestamp,         currency,         shopId     HAVING  (sm_all > 100000 and currency='RUB') OR (sm_all > 1500 and currency='USD') OR (sm_all > 1500 and currency='EUR') ) USING  timestamp,     shopId,     currency where sm_all > 0 ORDER BY percent DESC",
     "round": "0s",
     "table": "events_sink"
    }
   ]
  },
  {
   "title": "Deviation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": " Standard deviation",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "database": "analytic",
       "dateColDataType": "timestamp",
       "dateTimeColDataType": "eventTime",
       "dateTimeType": "TIMESTAMP",
       "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
       "query": "SELECT\n    $timeSeries as t,\n    stddevPop(amount/100) as cnt\nFROM fraud.payment\nWHERE\n    toDate($from) <= timestamp\n    and toDate($to) >= timestamp\n    and $from <= toDateTime(eventTime)\n    and $to >= toDateTime(eventTime)\n    and match(partyId, '$partyId')\n    and match(shopId, '$shopId')\nand shopId!='TEST'\nGROUP BY t, shopId\nORDER BY t",
       "rawQuery": "SELECT     (intDiv(eventTime, 60) * 60) * 1000 as t,     stddevPop(amount/100) as cnt FROM fraud.payment WHERE     toDate(1594117263) <= timestamp     and toDate(1594128065) >= timestamp     and 1594117263 <= toDateTime(eventTime)     and 1594128065 >= toDateTime(eventTime)     and match(partyId, '.')     and match(shopId, '.') and shopId!='TEST' GROUP BY t, shopId ORDER BY t",
       "round": "0s",
       "table": "events_sink"
      }
     ]
    },
    {
     "title": "Shop deviation > 20k",
     "type": "table",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 15 },
     "targets": [
      {
       "database": "analytic",
       "dateColDataType": "timestamp",
       "dateTimeColDataType": "eventTime",
       "dateTimeType": "TIMESTAMP",
       "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
       "query": "SELECT\n    $timeSeries as t,\n    shopId,\n    stddevPop(amount/100) as cnt\nFROM fraud.payment\nWHERE\n    toDate($from) <= timestamp\n    and toDate($to) >= timestamp\n    and $from <= toDateTime(eventTime)\n    and $to >= toDateTime(eventTime)\n    and match(partyId, '$partyId')\n    and match(shopId, '$shopId')\nGROUP BY t, shopId\nHAVING cnt > 20000\nORDER BY t",
       "rawQuery": "SELECT     (intDiv(eventTime, 60) * 60) * 1000 as t,     shopId,     stddevPop(amount/100) as cnt FROM fraud.payment WHERE     toDate(1594117263) <= timestamp     and toDate(1594128065) >= timestamp     and 1594117263 <= toDateTime(eventTime)     and 1594128065 >= toDateTime(eventTime)     and match(partyId, '.')     and match(shopId, '.') GROUP BY t, shopId HAVING cnt > 20000 ORDER BY t",
       "round": "0s",
       "table": "events_sink"
      }
     ]
    }
   ]
  },
  {
   "title": "sm",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top 20 shop sum",
     "type": "table",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
     "targets": [
      {
       "database": "analytic",
       "dateColDataType": "timestamp",
       "dateTimeType": "DATETIME",
       "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
       "query": "SELECT\n    currency as currency,\n    shopId as shop,\n    sum(amount / 100) as sm\nFROM fraud.payment\nWHERE\n    toDate($from) <= timestamp\n    and toDate($to) >= timestamp\n    and $from <= toDateTime(eventTime)\n    and $to >= toDateTime(eventTime)\n    and match(partyId, '$partyId')\n    and match(shopId, '$shopId')\nGROUP BY\n    shopId,\n    currency\nHAVING shopId!='TEST'\nORDER BY sm desc\nLIMIT 20",
       "rawQuery": "SELECT     currency as currency,     shopId as shop,     sum(amount / 100) as sm FROM fraud.payment WHERE     toDate(1594116784) <= timestamp     and toDate(1594127586) >= timestamp     and 1594116784 <= toDateTime(eventTime)     and 1594127586 >= toDateTime(eventTime)     and match(partyId, '.')     and match(shopId, '.') GROUP BY     shopId,     currency HAVING shopId!='TEST' ORDER BY sm desc LIMIT 20",
       "round": "0s",
       "table": "events_sink"
      }
     ]
    },
    {
     "title": "Sum by currency",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
     "format": "short",
     "valueName": "total",
     "targets": [
      {
       "database": "analytic",
       "dateColDataType": "timestamp",
       "dateTimeColDataType": "eventTime",
       "dateTimeType": "DATETIME",
       "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
       "query": "SELECT\n    sum(amount)/100 as cnt,\n    currency\nFROM fraud.payment\nWHERE\n    toDate($from) <= timestamp\n    and toDate($to) >= timestamp\n    and $from <= toDateTime(eventTime)\n    and $to >= toDateTime(eventTime)\n    and match(partyId, '$partyId')\n    and match(shopId, '$shopId')\n    and status='captured'\nand shopId!='TEST'\nGROUP BY currency\nORDER BY cnt desc\nLIMIT 20",
       "rawQuery": "SELECT     sum(amount)/100 as cnt,     currency FROM fraud.payment WHERE     toDate(1594116784) <= timestamp     and toDate(1594127586) >= timestamp     and 1594116784 <= toDateTime(eventTime)     and 1594127586 >= toDateTime(eventTime)     and match(partyId, '.')     and match(shopId, '.')     and status='captured' and shopId!='TEST' GROUP BY currency ORDER BY cnt desc LIMIT 20",
       "round": "0s",
       "table": "events_sink"
      }
     ]
    }
   ]
  },
  {
   "title": "Activity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top 20 bin activity",
     "type": "table",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
     "targets": [
      {
       "database": "analytic",
       "dateColDataType": "timestamp",
       "dateTimeColDataType": "eventTIme",
       "dateTimeType": "DATETIME",
       "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
       "query": "SELECT\n    bin, paymentCountry,\n    count(id) as cnt\nFROM fraud.payment\nWHERE toDate($from) <= timestamp and toDate($to) >= timestamp and  $from <= toDateTime(eventTime) and  $to >= toDateTime(eventTime) \nand match(partyId, '$partyId') and match(partyId, '$partyId') and match(shopId, '$shopId') \nand match(paymentCountry, '$paymentCountry') and match(bin, '$bin')  \nand (cardToken!='WLCeYVOp4bW1hJ3oCv8KG'\nand cardToken!='4xINpeuFJKxLPFGrdcrnUK'\nand cardToken!='vUp3YTW8wcLTS0VttdebO'\nand cardToken!='3zRjUhax48E1IY7wp7XZrS'\nand cardToken!='2ttEW2bq4CpuBRD0VOWW9g'\nand cardToken!='MfYHwQObqcIYlUTZD0v1y'\nand cardToken!='4Y3xD7ftAkQrAwpEds5lMk'\nand cardToken!='3q70aYBG6EH14ATRxxaom8'\nand cardToken!='quvSmP2lQwjouDkbF84Op'\nand cardToken!='4rqCK4KF5VwQL6o0TBzAHT'\nand cardToken!='6I2L72hZrsc2SHUbDIVoZF'\nand cardToken!='2X4iZv4CZ7XIG01DSgj4bv'\nand cardToken!='70DVkKLfywEJGaj7oqUY1Q'\nand cardToken!='7fAtmPASn44rNYieJfiv13'\nand cardToken!='2CL3xaXNWq76hEGcVMj1rF'\nand cardToken!='F3hq028Qsuo4KBNbRu8ud'\nand cardToken!='4XZts3K0zWi7JAfU9kK8Ku'\nand cardToken!='3csJuJyUbM7JmDCFiJoTfj'\nand cardToken!='8yCcCMHbhUWbH9Kh6ZtLW'\nand cardToken!='5iR9GSS7mzRFaYH1yROOiC'\nand cardToken!='7MZOauIs8yUtoKuCamADWv'\nand cardToken!='56kxngx6KgFFHrUbynNxi7')\nand shopId!='TEST'\nGROUP BY bin, paymentCountry\nORDER BY cnt desc\nlimit 20",
       "rawQuery": "SELECT     bin, paymentCountry,     count(id) as cnt FROM fraud.payment WHERE toDate(1594117263) <= timestamp and toDate(1594128065) >= timestamp and  1594117263 <= toDateTime(eventTime) and  1594128065 >= toDateTime(eventTime)  and match(partyId, '.') and match(partyId, '.') and match(shopId, '.')  and match(paymentCountry, '.') and match(bin, '.')   and (cardToken!='WLCeYVOp4bW1hJ3oCv8KG' and cardToken!='4xINpeuFJKxLPFGrdcrnUK' and cardToken!='vUp3YTW8wcLTS0VttdebO' and cardToken!='3zRjUhax48E1IY7wp7XZrS' and cardToken!='2ttEW2bq4CpuBRD0VOWW9g' and cardToken!='MfYHwQObqcIYlUTZD0v1y' and cardToken!='4Y3xD7ftAkQrAwpEds5lMk' and cardToken!='3q70aYBG6EH14ATRxxaom8' and cardToken!='quvSmP2lQwjouDkbF84Op' and cardToken!='4rqCK4KF5VwQL6o0TBzAHT' and cardToken!='6I2L72hZrsc2SHUbDIVoZF' and cardToken!='2X4iZv4CZ7XIG01DSgj4bv' and cardToken!='70DVkKLfywEJGaj7oqUY1Q' and cardToken!='7fAtmPASn44rNYieJfiv13' and cardToken!='2CL3xaXNWq76hEGcVMj1rF' and cardToken!='F3hq028Qsuo4KBNbRu8ud' and cardToken!='4XZts3K0zWi7JAfU9kK8Ku' and cardToken!='3csJuJyUbM7JmDCFiJoTfj' and cardToken!='8yCcCMHbhUWbH9Kh6ZtLW' and cardToken!='5iR9GSS7mzRFaYH1yROOiC' and cardToken!='7MZOauIs8yUtoKuCamADWv' and cardToken!='56kxngx6KgFFHrUbynNxi7') and shopId!='TEST' GROUP BY bin, paymentCountry ORDER BY cnt desc limit 20",
       "round": "0s",
       "table": "events_sink"
      }
     ]
    },
    {
     "title": "Top 20 country",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
     "format": "short",
     "valueName": "total",
     "targets": [
      {
       "database": "analytic",
       "dateColDataType": "timestamp",
       "dateTimeColDataType": "eventTime",
       "dateTimeType": "DATETIME",
       "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
       "query": "SELECT\n    count() as cnt,\n    bankCountry,\n    cnt * 100 /(SELECT count() FROM fraud.payment WHERE toDate($from) <= timestamp and toDate($to) >= timestamp and $from <= toDateTime(eventTime) and $to >= toDateTime(eventTime) and match(partyId, '$partyId') and match(shopId, '$shopId')) as percent\nFROM fraud.payment\nWHERE\n    toDate($from) <= timestamp\n    and toDate($to) >= timestamp\n    and $from <= toDateTime(eventTime)\n    and $to >= toDateTime(eventTime)\n    and match(partyId, '$partyId')\n    and match(shopId, '$shopId')\n    and shopId != 'TEST'\nGROUP BY bankCountry\nORDER BY percent desc\nLIMIT 20",
       "rawQuery": "SELECT     count() as cnt,     bankCountry,     cnt * 100 /(SELECT count() FROM fraud.payment WHERE toDate(1594117263) <= timestamp and toDate(1594128065) >= timestamp and 1594117263 <= toDateTime(eventTime) and 1594128065 >= toDateTime(eventTime) and match(partyId, '.') and match(shopId, '.')) as percent FROM fraud.payment WHERE     toDate(1594117263) <= timestamp     and toDate(1594128065) >= timestamp     and 1594117263 <= toDateTime(eventTime)     and 1594128065 >= toDateTime(eventTime)     and match(partyId, '.')     and match(shopId, '.')     and shopId != 'TEST' GROUP BY bankCountry ORDER BY percent desc LIMIT 20",
       "round": "0s",
       "table": "events_sink"
      }
     ]
    },
    {
     "title": "Provider activity",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 37 },
     "format": "short",
     "valueName": "total",
     "targets": [
      {
       "database": "analytic",
       "dateColDataType": "timestamp",
       "dateTimeColDataType": "eventTime",
       "dateTimeType": "DATETIME",
       "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
       "query": "SELECT\n    count() as cnt,\n    providerId,\n    cnt * 100 /(SELECT count() FROM fraud.payment WHERE toDate($from) <= timestamp and toDate($to) >= timestamp and $from <= toDateTime(eventTime) and $to >= toDateTime(eventTime) and match(partyId, '$partyId') and match(shopId, '$shopId')) as percent\nFROM fraud.payment\nWHERE\n    toDate($from) <= timestamp\n    and toDate($to) >= timestamp\n    and $from <= toDateTime(eventTime)\n    and $to >= toDateTime(eventTime)\n    and match(partyId, '$partyId')\n    and match(shopId, '$shopId')\n    and shopId != 'TEST'\nGROUP BY providerId\nORDER BY percent desc\nLIMIT 20",
       "rawQuery": "SELECT     count() as cnt,     providerId,     cnt * 100 /(SELECT count() FROM fraud.payment WHERE toDate(1594117263) <= timestamp and toDate(1594128065) >= timestamp and 1594117263 <= toDateTime(eventTime) and 1594128065 >= toDateTime(eventTime) and match(partyId, '.') and match(shopId, '.')) as percent FROM fraud.payment WHERE     toDate(1594117263) <= timestamp     and toDate(1594128065) >= timestamp     and 1594117263 <= toDateTime(eventTime)     and 1594128065 >= toDateTime(eventTime)     and match(partyId, '.')     and match(shopId, '.')     and shopId != 'TEST' GROUP BY providerId ORDER BY percent desc LIMIT 20",
       "round": "0s",
       "table": "events_sink"
      }
     ]
    },
    {
     "title": "Payment system activity",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 37 },
     "format": "short",
     "valueName": "total",
     "targets": [
      {
       "database": "analytic",
       "dateColDataType": "timestamp",
       "dateTimeColDataType": "eventTime",
       "dateTimeType": "DATETIME",
       "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
       "query": "SELECT\n    count() as cnt,\n    paymentSystem,\n    cnt * 100 /(SELECT count() FROM fraud.payment WHERE toDate($from) <= timestamp and toDate($to) >= timestamp and $from <= toDateTime(eventTime) and $to >= toDateTime(eventTime) and match(partyId, '$partyId') and match(shopId, '$shopId')) as percent\nFROM fraud.payment\nWHERE\n    toDate($from) <= timestamp\n    and toDate($to) >= timestamp\n    and $from <= toDateTime(eventTime)\n    and $to >= toDateTime(eventTime)\n    and match(partyId, '$partyId')\n    and match(shopId, '$shopId')\n    and paymentSystem != ''\n    and shopId != 'TEST'\nGROUP BY paymentSystem\nORDER BY percent desc",
       "rawQuery": "SELECT     count() as cnt,     paymentSystem,     cnt * 100 /(SELECT count() FROM fraud.payment WHERE toDate(1594117263) <= timestamp and toDate(1594128065) >= timestamp and 1594117263 <= toDateTime(eventTime) and 1594128065 >= toDateTime(eventTime) and match(partyId, '.') and match(shopId, '.')) as percent FROM fraud.payment WHERE     toDate(1594117263) <= timestamp     and toDate(1594128065) >= timestamp     and 1594117263 <= toDateTime(eventTime)     and 1594128065 >= toDateTime(eventTime)     and match(partyId, '.')     and match(shopId, '.')     and paymentSystem != ''     and shopId != 'TEST' GROUP BY paymentSystem ORDER BY percent desc",
       "round": "0s",
       "table": "events_sink"
      }
     ]
    }
   ]
  },
  {
   "title": "Errors and country",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top 20 error",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
     "format": "short",
     "valueName": "total",
     "targets": [
      {
       "database": "analytic",
       "dateColDataType": "timestamp",
       "dateTimeColDataType": "eventTime",
       "dateTimeType": "DATETIME",
       "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
       "query": "SELECT\n    count() as cnt,\n    errorCode\nFROM fraud.payment\nWHERE\n    toDate($from) <= timestamp\n    and toDate($to) >= timestamp\n    and $from <= toDateTime(eventTime)\n    and $to >= toDateTime(eventTime)\n    and status = 'failed'\n    and match(partyId, '$partyId')\n    and match(shopId, '$shopId')\n    and match(paymentCountry, '$paymentCountry')\n    and shopId != 'TEST'\nGROUP BY errorCode\nORDER BY cnt desc\nLIMIT 20",
       "rawQuery": "SELECT     count() as cnt,     errorCode FROM fraud.payment WHERE     toDate(1594117417) <= timestamp     and toDate(1594128219) >= timestamp     and 1594117417 <= toDateTime(eventTime)     and 1594128219 >= toDateTime(eventTime)     and status = 'failed'     and match(partyId, '.')     and match(shopId, '.')     and match(paymentCountry, '.')     and shopId != 'TEST' GROUP BY errorCode ORDER BY cnt desc LIMIT 20",
       "round": "0s",
       "table": "events_sink"
      }
     ]
    },
    {
     "title": "Fraud Top 20 error",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
     "format": "short",
     "valueName": "total",
     "targets": [
      {
       "database": "fraud",
       "dateColDataType": "timestamp",
       "dateTimeColDataType": "eventTime",
       "dateTimeType": "DATETIME",
       "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
       "query": "SELECT\n    count() as cnt,\n    checkedTemplate,\n    checkedRule,\n    bankCountry\nFROM fraud.events_unique\nWHERE\n    toDate($from) <= timestamp\n    and toDate($to) >= timestamp\n    and $from <= toDateTime(eventTime)\n    and $to >= toDateTime(eventTime)\n    and match(partyId, '$partyId')\n    and match(shopId, '$shopId')\n    and match(bankCountry, '$paymentCountry')\n    AND resultStatus = 'DECLINE'\n    and shopId != 'TEST'\nGROUP BY\n    checkedTemplate,\n    checkedRule,\n    bankCountry\nORDER BY cnt desc\nLIMIT 30",
       "rawQuery": "SELECT     count() as cnt,     checkedTemplate,     checkedRule,     bankCountry FROM fraud.events_unique WHERE     toDate(1594117417) <= timestamp     and toDate(1594128219) >= timestamp     and 1594117417 <= toDateTime(eventTime)     and 1594128219 >= toDateTime(eventTime)     and match(partyId, '.')     and match(shopId, '.')     and match(bankCountry, '.')     AND resultStatus = 'DECLINE'     and shopId != 'TEST' GROUP BY     checkedTemplate,     checkedRule,     bankCountry ORDER BY cnt desc LIMIT 30",
       "round": "0s",
       "table": "events_unique"
      }
     ]
    },
    {
     "title": "Success rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "database": "analytic",
       "dateColDataType": "timestamp",
       "dateTimeColDataType": "eventTime",
       "dateTimeType": "TIMESTAMP",
       "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
       "query": "SELECT\n    t,\n    low * 100 / all captured,\n    fatal * 100 / all failed,\n    cancell * 100 / all cancelled\nFROM\n(\n    SELECT\n        (intDiv(eventTime, 60) * 60) * 1000 AS t,\n        countIf(status = 'captured') AS low,\n        countIf(status = 'failed') AS fatal,\n        countIf(status = 'cancelled') AS cancell,\n        count() as all\n    FROM fraud.payment\n    WHERE\n        timestamp >= toDate($from)\n        and timestamp <= toDate($to)\n        AND eventTime >= $from\n        and eventTime <= $to\n        and match(partyId, '$partyId')\n        and match(shopId, '$shopId')\n        and shopId!='TEST'\n    GROUP BY t\n    ORDER BY t\n)",
       "rawQuery": "SELECT     t,     low * 100 / all captured,     fatal * 100 / all failed,     cancell * 100 / all cancelled FROM (     SELECT         (intDiv(eventTime, 60) * 60) * 1000 AS t,         countIf(status = 'captured') AS low,         countIf(status = 'failed') AS fatal,         countIf(status = 'cancelled') AS cancell,         count() as all     FROM fraud.payment     WHERE         timestamp >= toDate(1594117417)         and timestamp <= toDate(1594128219)         AND eventTime >= 1594117417         and eventTime <= 1594128219         and match(partyId, '.')         and match(shopId, '.')         and shopId!='TEST'     GROUP BY t     ORDER BY t )",
       "round": "0s",
       "table": "events_sink"
      }
     ]
    },
    {
     "title": "Fraud rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "database": "analytic",
       "dateColDataType": "timestamp",
       "dateTimeColDataType": "eventTime",
       "dateTimeType": "TIMESTAMP",
       "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
       "query": "SELECT\n    t,\n    low * 100 / all normal,\n    fatal * 100 / all fraud\nFROM\n(\n    SELECT\n        (intDiv(eventTime, 60) * 60) * 1000 AS t,\n        countIf(status = 'captured' or status='cancelled') AS low,\n        countIf(status = 'failed' and errorCode='no_route_found:risk_score_is_too_high') AS fatal,\n        count() as all\n    FROM fraud.payment\n    WHERE\n        timestamp >= toDate($from)\n        and timestamp <= toDate($to)\n        AND eventTime >= $from\n        and eventTime <= $to\n        and match(partyId, '$partyId')\n        and match(shopId, '$shopId')\n        and shopId!='TEST'\n    GROUP BY t\n    ORDER BY t\n)",
       "rawQuery": "SELECT     t,     low * 100 / all normal,     fatal * 100 / all fraud FROM (     SELECT         (intDiv(eventTime, 60) * 60) * 1000 AS t,         countIf(status = 'captured' or status='cancelled') AS low,         countIf(status = 'failed' and errorCode='no_route_found:risk_score_is_too_high') AS fatal,         count() as all     FROM fraud.payment     WHERE         timestamp >= toDate(1594117417)         and timestamp <= toDate(1594128219)         AND eventTime >= 1594117417         and eventTime <= 1594128219         and match(partyId, '.')         and match(shopId, '.')         and shopId!='TEST'     GROUP BY t     ORDER BY t )",
       "round": "0s",
       "table": "events_sink"
      }
     ]
    }
   ]
  }
 ]
}