{
 "title": "antifraud-prod",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "partyId", "label": "partyId", "query": "." },
   { "name": "shopId", "label": "shopId", "query": "." },
   { "name": "resultStatus", "label": "resultStatus", "query": "." },
   { "name": "email", "label": "email", "query": ".*" },
   { "name": "maskedPan", "label": "maskedPan", "query": ".*" },
   { "name": "invoiceId", "label": "invoice", "query": "." },
   { "name": "bankCountry", "label": "bankCountry", "query": "." },
   { "name": "cardToken", "label": "cardToken", "query": "." },
   { "name": "fingerprint", "label": "fingerprint", "query": ".*" }
  ]
 },
 "panels": [
  {
   "title": "FB results",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "database": "fraud",
     "dateColDataType": "timestamp",
     "dateTimeColDataType": "eventTime",
     "dateTimeType": "TIMESTAMP",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "SELECT\n    toDateTime(eventTime) as eventTime,\n    partyId,\n    shopId,\n    email,\n    amount / 100 as amount,\n    currency as cur,\n    concat(bin, ' ', maskedPan) as card,\n        concat(invoiceId, '.', paymentId) as payment,\n    cardToken,\n    bankCountry,\n    fingerprint,\n    ip,\n    bankName,\n    resultStatus,\n    country,\n    checkedRule as checked,\n    checkedTemplate\nFROM $table\nWHERE\n    toDate($from) <= timestamp\n    and toDate($to) >= timestamp\n    and $from <= toDateTime(eventTime)\n    and $to >= toDateTime(eventTime)\n    and match(partyId, '$partyId')\n    and match(shopId, '$shopId')\n    and match(resultStatus, '$resultStatus')\n    and match(bankCountry, '$bankCountry')\n    and match(cardToken, '$cardToken')\n    and match(fingerprint, '$fingerprint')\n    and match(invoiceId, '$invoiceId')\n    and match(email, '$email')\n    and match(concat(bin, ' ', maskedPan), '$maskedPan')\nLIMIT 100",
     "rawQuery": "SELECT     toDateTime(eventTime) as eventTime,     partyId,     shopId,     email,     amount / 100 as amount,     currency as cur,     status,     id as chargebackId,     paymentId,     bankCountry,     cardToken,     paymentSystem,     providerId,     status,     ip,     fingerprint,     terminal FROM fraud.chargeback WHERE     toDate(1594181693) <= timestamp     and toDate(1594203295) >= timestamp     and 1594181693 <= toDateTime(eventTime)     and 1594203295 >= toDateTime(eventTime)     and match(partyId, '.')     and match(shopId, '.')     and (email=='' or match(email, '.'))     and match(bankCountry, '.')     and match(cardToken, '.')     and(fingerprint=='' or  match(fingerprint, '.'))     and match(paymentId, '.') LIMIT 100",
     "round": "0s",
     "table": "events_unique",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Processing Results",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "database": "analytic",
     "dateColDataType": "timestamp",
     "dateTimeColDataType": "eventTime",
     "dateTimeType": "TIMESTAMP",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "SELECT\n    toDateTime(eventTime) as eventTime,\n    partyId,\n    shopId,\n    email,\n    amount / 100 as amount,\n    currency as cur,\n    concat(bin, ' ', maskedPan) as card,\n    id as payment,\n    cardToken,\n    bankCountry,\n    fingerprint,\n    ip,\n    status,\n    errorReason,\n    errorCode,\n    paymentSystem,\n    paymentCountry,\n    paymentTool,\n    providerId,\n    terminal\nFROM fraud.payment\nWHERE\n    toDate($from) <= timestamp\n    and toDate($to) >= timestamp\n    and $from <= toDateTime(eventTime)\n    and $to >= toDateTime(eventTime)\n    and match(partyId, '$partyId')\n    and match(shopId, '$shopId')\n    and match(email, '$email')\n    and match(bankCountry, '$bankCountry')\n    and match(cardToken, '$cardToken')\n    and match(fingerprint, '$fingerprint')\n    and match(concat(bin, ' ', maskedPan), '$maskedPan')\nLIMIT 100",
     "rawQuery": "SELECT     toDateTime(eventTime) as eventTime,     partyId,     shopId,     email,     amount / 100 as amount,     currency as cur,     concat(bin, ' ', maskedPan) as card,     id as payment,     cardToken,     bankCountry,     fingerprint,     ip,     status,     errorReason,     errorCode,     paymentSystem,     paymentCountry,     paymentTool,     providerId,     terminal FROM fraud.payment WHERE     toDate(1594181693) <= timestamp     and toDate(1594203295) >= timestamp     and 1594181693 <= toDateTime(eventTime)     and 1594203295 >= toDateTime(eventTime)     and match(partyId, '.')     and match(shopId, '.')     and match(email, '.')     and match(bankCountry, '.')     and match(cardToken, '.')     and match(fingerprint, '.')     and match(concat(bin, ' ', maskedPan), '.*') LIMIT 100",
     "round": "0s",
     "table": "events_sink",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Refunds Results",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "database": "analytic",
     "dateColDataType": "timestamp",
     "dateTimeColDataType": "eventTime",
     "dateTimeType": "TIMESTAMP",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "SELECT\n    toDateTime(eventTime) as eventTime,\n    partyId,\n    shopId,\n    email,\n    amount / 100 as amount,\n    currency as cur,\n        status,\n    id as refundId,\n    paymentId,\n    bankCountry,\n    cardToken,\n    paymentSystem,\n    providerId,\n    errorReason,\n    errorCode,\n    ip,\n    fingerprint,\n    terminal\nFROM fraud.refund\nWHERE\n    toDate($from) <= timestamp\n    and toDate($to) >= timestamp\n    and $from <= toDateTime(eventTime)\n    and $to >= toDateTime(eventTime)\n    and match(partyId, '$partyId')\n    and match(shopId, '$shopId')\n    and (email=='' or match(email, '$email'))\n    and match(bankCountry, '$bankCountry')\n    and match(cardToken, '$cardToken')\n    and(fingerprint=='' or  match(fingerprint, '$fingerprint'))\nLIMIT 100",
     "rawQuery": "SELECT     toDateTime(eventTime) as eventTime,     partyId,     shopId,     email,     amount / 100 as amount,     currency as cur,         status,     id as refundId,     paymentId,     bankCountry,     cardToken,     paymentSystem,     providerId,     errorReason,     errorCode,     ip,     fingerprint,     terminal FROM fraud.refund WHERE     toDate(1594181693) <= timestamp     and toDate(1594203295) >= timestamp     and 1594181693 <= toDateTime(eventTime)     and 1594203295 >= toDateTime(eventTime)     and match(partyId, '.')     and match(shopId, '.')     and (email=='' or match(email, '.'))     and match(bankCountry, '.')     and match(cardToken, '.')     and(fingerprint=='' or  match(fingerprint, '.')) LIMIT 100",
     "round": "0s",
     "table": "events_sink_refund",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Chargeback Results",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "database": "analytic",
     "dateColDataType": "timestamp",
     "dateTimeColDataType": "eventTime",
     "dateTimeType": "TIMESTAMP",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "SELECT\n    toDateTime(eventTime) as eventTime,\n    partyId,\n    shopId,\n    email,\n    amount / 100 as amount,\n    currency as cur,\n    status,\n    id as chargebackId,\n    paymentId,\n    bankCountry,\n    cardToken,\n    paymentSystem,\n    providerId,\n    status,\n    ip,\n    fingerprint,\n    terminal\nFROM fraud.chargeback\nWHERE\n    toDate($from) <= timestamp\n    and toDate($to) >= timestamp\n    and $from <= toDateTime(eventTime)\n    and $to >= toDateTime(eventTime)\n    and match(partyId, '$partyId')\n    and match(shopId, '$shopId')\n    and (email=='' or match(email, '$email'))\n    and match(bankCountry, '$bankCountry')\n    and match(cardToken, '$cardToken')\n    and(fingerprint=='' or  match(fingerprint, '$fingerprint'))\n    and match(paymentId, '$invoiceId')\nLIMIT 100",
     "rawQuery": "SELECT     toDateTime(eventTime) as eventTime,     partyId,     shopId,     email,     amount / 100 as amount,     currency as cur,     status,     id as chargebackId,     paymentId,     bankCountry,     cardToken,     paymentSystem,     providerId,     status,     ip,     fingerprint,     terminal FROM fraud.chargeback WHERE     toDate(1594181693) <= timestamp     and toDate(1594203295) >= timestamp     and 1594181693 <= toDateTime(eventTime)     and 1594203295 >= toDateTime(eventTime)     and match(partyId, '.')     and match(shopId, '.')     and (email=='' or match(email, '.'))     and match(bankCountry, '.')     and match(cardToken, '.')     and(fingerprint=='' or  match(fingerprint, '.'))     and match(paymentId, '.') LIMIT 100",
     "round": "0s",
     "table": "events_sink_chargeback",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}